# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PhraseArt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PhraseArt
  # https://facebook.github.io/react-native/docs/integration-with-existing-apps.html
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Firebase
  pod 'Firebase/Core', '~> 5.9.0'
  pod 'Firebase/RemoteConfig', '~> 5.9.0'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.7'
  # FirebaseAnalyticsが依存しているGoogleAppMeasurementのバージョンミスマッチが起きるので、GoogleAppMeasurementのバージョンを指定する
  # @see https://github.com/invertase/react-native-firebase/issues/1633
  pod 'GoogleAppMeasurement', '~> 5.2.0'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  target 'PhraseArt-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhraseArtTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

# Duplicate Symbols を回避する
# https://github.com/react-community/react-native-maps/issues/718#issuecomment-358103368
post_install do |installer|
  installer.pods_project.targets.each do |target|
    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(React yoga)

    if targets_to_ignore.include? target.name
      target.remove_from_project
    end
  end
end
